### PR TITLE
Add translations for assistant's embedding_not_supported key

### PR DESCRIPTION
**Pull request by twinkarma**

### CODE REVIEW

**Comment by twinkarma** [comment]
@Sallaa translation's been checked and hopefully ready to be merged.

**Comment by Sallaa** [comment]
@twinkarma Looks like there is an error around line 55, could you have a look? Could be a whitespace instead of a tab, a missing tab, or maybe something else.

Also are you able to see that the check failed? We have added an automation to inform if there is a formatting issue in the files.

https://github.com/AFP-Medialab/InVID-Translations/blob/02ba5892461b49dcc47c1c25fd6d363ee65c4e83/components/NavItems/tools/Assistant.tsv

**Comment by twinkarma** [comment]
@Sallaa No I'm not able to see the jenkins report, looks like I'll need the login credentials? I've gone in to fix the text but the same error is still showing. The error message is not very helpful when there's 5 paragraph's worth of text on that single line 55!

**Comment by twinkarma** [comment]
Also I didn't modify line 55 so it's strange that there's an error now, has there been new checks implemented since?

**Comment by Sallaa** [comment]
@twinkarma I will have a look today and see if I can find the issue, maybe the lint is a bit off and the issue is not on that line. Yeah the error messages are not helpful at all 👎 -- I'm trying to push for having `.json` only translations (i18n) but we haven't fully migrated yet.

No, we have not added more checks, and Jenkins is not helpful either on what's causing the error :/ -- I will ask @AFPMedialab to give you access to logs next week.

Also, we are planning to release at the end of this week / next week, do you want this translation included? If yes we can merge this into `v0.79.1` instead.

**Comment by Sallaa** [comment]
I have fixed some quotation marks and other broken translations, can you pull my changes from `v0.80` or `v0.79.1`? This should fix the automated check for your PR

**Comment by twinkarma** [comment]
@Sallaa I'm still getting the error even though I've rebased from your v0.80 branch. If you have a look at the diff it's literally only changing the last two lines of the file.

**Comment by Sallaa** [comment]
@twinkarma thank you, I had a look and will approve it. I found that the errors are prior to your PR anyways. You may want to test all the languages for the assistant, it may be easier to see if there is a problem visually. I fixed some broken html tags that got lost in translations, but there may be more to it.

**Comment by twinkarma** [comment]
Thanks @Sallaa I'll give the translations another check for the malformed html

**Pull request merged**
