### PR TITLE
Asssistant video download instruction banner text

### PR DESCRIPTION
**Pull request by twinkarma**
Translations for PR: https://github.com/AFP-Medialab/verification-plugin/pull/552

### CODE REVIEW

**Comment by twinkarma** [comment]
@Sallaa @ttramb here's some text for the upcoming video services fix. Struggling with combining html tags and Arabic. Do you have any advice?

**Comment by Sallaa** [comment]
@twinkarma  What is your workflow to get the Arabic translations? I have found that LLMs get the best results for generating these TSV lines.

I know that @dteyssou is also using Google Translate but I think it breaks the html tags

**Comment by twinkarma** [comment]
I've also been using google translate. Will be using LLM to do the initial translation from now on, thanks! I've also fixed the illegal quoting issue and the table should render correctly on github now.

**Comment by Sallaa** [comment]
Great! Do you need to do any more change or is it ready to be merged?

**Comment by twinkarma** [comment]
I've not had the translations checked yet, let me put it to the GATE team first

**Comment by twinkarma** [comment]
@Sallaa do you have anyone who can verify Greek, Italian and German translations on your side? If you it'd be great if we can get the last four rows checked:

https://github.com/twinkarma/InVID-Translations/blob/assistant/video-download-instructions/components/NavItems/tools/Assistant.tsv

Also does the French translation look ok to you?

**Comment by Sallaa** [comment]
I will ask @dteyssou to have a look this week. He could help with Italian and we may have someone at AFP for checking the German language. I also approved #92 so you may need to merge `v0.82` into your branch

**Comment by Sallaa** [comment]
@twinkarma translations look good to me. Could you resolve the final conflicts? I will merge it after

**Comment by twinkarma** [comment]
Thanks @Sallaa , I've fixed the conflict

**Pull request merged**
